# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTweet',
            fields=[
                ('tweetID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
                ('userLocation', models.CharField(max_length=100)),
                ('tweetLocation', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('isretweeted', models.NullBooleanField()),
                ('hashtags', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('activateLocation', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=100)),
                ('locationRadius', models.CharField(default='0km', max_length=5)),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawtweet',
            name='SearchID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webApp.Search'),
        ),
    ]
